### ISSUE TITLE
Publish v2.1.0 - Added Echo

### ISSUE THREAD

**Issue by fatchan** [fatchan/overwatch-stats-api#13]
ill update the module some time this weekend

**Comment by EndBug** [comment]
Awesome! I'll update some stuff for typings and linting since it's been a while since I've looked at this repo 😅

**Comment by fatchan** [comment]
Well I think as usual we have to wait a bit more for blizzard to update their site :joy: because I checked a profile of somebody I know played echo and still not there :man_facepalming:

**Comment by EndBug** [comment]
Yeah, maybe it's because it's still only in the PTR, guess we'll have to wait then

**Comment by fatchan** [comment]
Oh yeah that explains it. I only saw echo on a twitch stream, didnt realise it was PTR and i havent played OW in ages

**Comment by EndBug** [comment]
I've added the ID since they've just released it. Let me know when you add it to the live API 👍

**Comment by EndBug** [comment]
I've already tested the changes with [this](https://playoverwatch.com/en-us/career/pc/Samito-11462) user, bumped the version and added the tag. It only needs to be published to npm
